environment:
  matrix:
    - QTDIR: C:\Qt\5.12.6\mingw73_32\bin
      CC: C:\Qt\Tools\mingw730_32\bin\gcc.exe
      CXX: C:\Qt\Tools\mingw730_32\bin\g++.exe

install:
  - set PATH=C:\Qt\5.12.6\mingw73_32\bin;C:\Qt\5.12.6\mingw73_64\bin;C:\Qt\Tools\CMake_32\bin;C:\Qt\Tools\CMake_64\bin;C:\Qt\Tools\mingw730_32\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%

build_script:
  - cp C:\Qt\Tools\mingw730_32\bin\mingw32-make.exe C:\Qt\Tools\mingw730_32\bin\make.exe
  - cd C:\
  - git clone https://github.com/google/googletest.git
  - mv googletest GTest
  - mkdir GTest\build
  - cd GTest\build
  - cmake ..
  - ls googletest
  - ls googlemock
  - cd C:\projects\galacticwar
  - mkdir build
  - cd build
  - cmake ../ -G "MSYS Makefiles"
  - make -j
