configuration:
  - BuildApp
  - BuildUts
  - RunUts

install:
  - set PATH=C:\Qt\5.12.10\mingw73_32\bin;C:\Qt\5.12.10\mingw73_64\bin;C:\Qt\Tools\CMake_32\bin;C:\Qt\Tools\CMake_64\bin;C:\Qt\Tools\mingw730_32\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%

environment:
  QTDIR: C:\Qt\5.12.10\mingw73_32\bin
  CC: C:\Qt\Tools\mingw730_32\bin\gcc.exe
  CXX: C:\Qt\Tools\mingw730_32\bin\g++.exe

before_build:
  - cp C:\Qt\Tools\mingw730_32\bin\mingw32-make.exe C:\Qt\Tools\mingw730_32\bin\make.exe
  - cd C:\
  - git clone https://github.com/google/googletest.git
  - mv googletest GTest
  - mkdir GTest\build
  - cd GTest\build
  - cmake  ../ -G "MSYS Makefiles"
  - cd C:\projects\galacticwar
  - mkdir build
  - cd build

for:
  - matrix:
      only:
        - configuration: BuildApp
    build_script:
      - cmake ../ -G "MSYS Makefiles"
      - make -j app
  - matrix:
      only:
        - configuration: BuildUts
    build_script:
      - cmake ../ -G "MSYS Makefiles"
      - make -j buildut
  - matrix:
      only:
        - configuration: RunUts
    build_script:
      - mkdir tests\platforms
      - cp C:\Qt\5.12.10\mingw73_32\plugins\platforms\qwindows.dll tests\platforms
      - mkdir tests\mediaservice
      - cp C:\Qt\5.12.10\mingw73_32\plugins\mediaservice\dsengine.dll tests\mediaservice
      - cp C:\Qt\5.12.10\mingw73_32\plugins\mediaservice\qtmedia_audioengine.dll tests\mediaservice
      - cmake ../ -G "MSYS Makefiles"
      - make runut
